---
- name: IOS Show command
  hosts: switches_centre
  gather_facts: false
  connection: local

  tasks:
    - name: SHOW COMMANDS
      ios_command:
        commands: 
          - show version
...      
